DROP TABLE dependente ;
DROP TABLE reserva ;
DROP TABLE hospedagem ;
DROP TABLE avaliacao ;
DROP TABLE venda ;
DROP TABLE alocacao ;
DROP TABLE produto;
DROP TABLE passeio_turistico;
DROP TABLE lavanderia;
DROP TABLE frigobar;
DROP TABLE restaurante;
DROP TABLE estacionamento;
DROP TABLE bar;
DROP TABLE cliente;
DROP TABLE funcionario ;
DROP TABLE quarto;
DROP TABLE servico;
